---
- name: Install Samba server
  dnf:
    name: samba
    state: present

- name: Ensure Samba is enabled and running
  systemd:
    name: smb
    enabled: yes
    state: started

- name: Deploy Samba configuration
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
  notify: Restart Samba

- name: Ensure firewall allows Samba traffic
  firewalld:
    service: samba
    permanent: yes
    state: enabled
    immediate: yes
